### ISSUE TITLE
Routing isn't working, and won't build to Now

### ISSUE THREAD

**Issue by szul** [szul/october.codes#1]
Hey @paulogdm, any clue on this? The static routes in `now.json` other than the index don't work with `now dev`, and although `now dev` will build locally, and run (other than the two static HTML pages in the routes), pushing to Now via `now` gives:

```
> Error! You defined 1 build that did not match any source files (please ensure they are NOT defined in .nowignore):
- {"src":"package.json","use":"@now/static-build","config":{"distDir":"./"}}
```

**Comment by leo** [comment]
@szul So, there are two things:

---

> The static routes in now.json other than the index don't work with now dev

You have this line in your `now.json`:

```
{ "src": "*.html", "use": "@now/static" }
```

Since you're using `*`, any files on the root level are matched (that's why the index route is working, because `index.html` is on the main level).

If you set this instead:

```
{ "src": "**/*.html", "use": "@now/static" }
```

You will also match HTML files that are part of any sub directory. Which, in turn, will make the routes work that are not on the root level (like `^/library/research/nasa-pmc-mirror`).

----

> Error! You defined 1 build that did not match any source files (please ensure they are NOT defined in .nowignore):
> - {"src":"package.json","use":"@now/static-build","config":{"distDir":"./"}}

This error occurs because of this line:

```
{ "src": "*.json", "use": "@now/static" }
```

Since you are setting `package.json` to be served statically, the fourth Build cannot use the file to run `@now/static-build`.

I have not yet been able to ascertain why ☝️ occurs only on `now`, not `now dev`, but I'll have my team's Now CLI expert dig deeper into this and get back to you.

**Comment by szul** [comment]
@leo Okay, I'll make these changes and see what happens. Is this documented anywhere on the web site, or is there a "troubleshooting" area this can be added to? I'm going to be converting most of the application I build to Zeit hosting via Now v2, and any issues that come up and get resolved, I can do  PR to the docs.

**Comment by leo** [comment]
@szul Thank you for your kind offer.

1. The `*.html` => `**/*.html` suggestion should be documented [here](https://zeit.co/docs/v2/deployments/builders/overview/#how-to-use-builders).
2. The second suggestion should not be documented yet, as I'll verify whether `now` or `now dev` have the right behaviour for this.

If you'd like to do a PR for #1 [here](https://github.com/zeit/docs), that'd be amazing. However, the team can also take care of that for you, if not!

**Comment by szul** [comment]
This all worked great. Thanks for looking into it!
